### ISSUE TITLE
Keycloak browser-like testing

### ISSUE THREAD

**Issue by bsoniam** [cloudtrust/acceptance-tool#4]
For the modules coded by the CT team: keycloak-wsfed and keycloak-authorization, a browser-like testing is required in order to validate the interface used by a user. 
For this we can use: https://github.com/cobrateam/splinter (https://splinter.readthedocs.io/en/latest/drivers/chrome.html#using-headless-option-for-chrome) 
or selenium

**Comment by basbeu** [comment]
Archiving the repository
