### ISSUE TITLE
Test that single logout works correctly when keycloak is used as a SAML identity broker with keycloak 4.0+

### ISSUE THREAD

**Issue by AlistairDoswald** [cloudtrust/acceptance-tool#5]
Currently we have a null pointer exception when using keyclok as a SAML identity broker. This bug is known and described in [this keycloak issue](https://issues.jboss.org/browse/KEYCLOAK-6474). However the issue is marked as corrected in version 4.0.0.Beta1, so the issue should be retested when Cloudtrust moves to 4.0.0.Final+.

The internal story to test is: Story CT-TC-SAML-BROKER-LOGOUT-SIMPLE.

**Comment by basbeu** [comment]
Archiving the repository
